const LANGUAGES = {
    ES: {
        Home: 'Inicio',
        Patient: 'Paciente',
        Patients: 'Pacientes',
        Profesional: 'Profesional',
        Profesionals: 'Profesionales',
        Configuration: 'Configuración',
        Search: 'Buscar',
        Notes: 'Notas',
        Photos: 'Fotografías',
        Files: 'Archivos',
        Turns: 'Turnos',
        Treatments: 'Tratamientos',
        Main: 'Principal',
        Profile: 'Perfil',
        headings: {
            TodaysTurns: 'Turnos de hoy'
        },
        buttons: {
            Add: 'Añadir',
            SeeOnAgenda: 'Ver en agenda',
            LogOut: 'Cerrar Sesión',
            Save: 'Guardar',
            Confirm: 'Confirmar',
            Cancel: 'Cancelar',
            Edit: 'Editar',
            Delete: 'Eliminar',
            Turn: 'Turno',
            Exception: 'Excepción',
            Reminder: 'Recordatorio',
        },
        rows: {
            Surnames: 'Apellidos',
            Names: 'Nombres',
            Birthdate: 'Fecha de Nacimiento',
            Phone: 'Teléfono',
            Username: 'Usuario',
            Mail: 'Correo',
            Address: 'Dirección',
            Role: 'Rol',
            Charge: 'Cargo',
            Filename: 'Nombre',
            Description: 'Descripción',
            UpdatedAt: 'Última modificación',
            Password: 'Contraseña',
            Date: 'Fecha',
            Time: 'Hora',
            Duration: 'Duración',
        },
        configuration: {
            Language: 'Idioma',
            DarkMode: 'Modo oscuro'
        },
        messages: {
            NoResults: 'No se han encontrado resultados',
            Loading: 'Cargando',
            LogIn: 'Iniciar Sesión',
            YearsOld: 'Años',
            NotNullable: 'El campo no puede estar vacio',
            FieldRequired: 'El campo es obligatorio',
            InvalidDate: 'La fecha ingresada no es válida',
            InvalidFormat: 'El formato no es el correcto',
            WriteHere: 'Escriba aquí...',
            ConfirmDelete: '¿Está seguro que desea eliminar el siguiente elemento?',
            PatientCreated: 'Nuevo paciente añadido satisfactoriamente',
            PatientUpdated: 'Paciente editado satisfactoriamente',
            PatientDeleted: 'Paciente eliminado satisfactoriamente',
            NoteCreated: 'Nueva nota añadida satisfactoriamente',
            NoteUpdated: 'Nota editada satisfactoriamente',
            NoteDeleted: 'Nota eliminada satisfactoriamente',
            PageNotFound: 'Página no encontrada',
        },
        days: [ 'Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado' ],
        string: 'es-ES',
    },
    EN: {
        Home: 'Home',
        Patient: 'Patient',
        Patients: 'Patients',
        Profesional: 'Profesional',
        Profesionals: 'Profesionals',
        Configuration: 'Configuration',
        Search: 'Search',
        Notes: 'Notes',
        Photos: 'Photos',
        Files: 'Files',
        Turns: 'Turns',
        Treatments: 'Treatments',
        Main: 'Main',
        Profile: 'Profile',
        headings: {
            TodaysTurns: "Today's Turns"
        },
        buttons: {
            Add: 'Add',
            SeeOnAgenda: 'See on agenda',
            LogOut: 'Logout',
            Save: 'Save',
            Confirm: 'Confirm',
            Cancel: 'Cancel',
            Edit: 'Edit',
            Delete: 'Delete',
            Turn: 'Turn',
            Exception: 'Exception',
            Reminder: 'Reminder',
        },
        rows: {
            Surnames: 'Surnames',
            Names: 'Names',
            Birthdate: 'Birthdate',
            Phone: 'Phone',
            Username: 'Username',        
            Mail: 'Mail',
            Address: 'Address',
            Role: 'Role',
            Charge: 'Charge',
            Filename: 'Filename',
            Description: 'Description',
            UpdatedAt: 'Updated at',
            Password: 'Password',
            Date: 'Date',
            Time: 'Time',
            Duration: 'Duration',
        },
        configuration: {
            Language: 'Language',
            DarkMode: 'Dark mode'
        },
        messages: {
            NoResults: 'No results found',
            Loading: 'Loading',
            LogIn: 'Login',
            YearsOld: 'Years old',
            NotNullable: 'The field cannot be empty',
            FieldRequired: 'The field is required',
            InvalidDate: 'The date entered is not valid',
            InvalidFormat: 'The format is not valid',
            WriteHere: 'Write here...',
            ConfirmDelete: 'Do you confirm that you want to delete the following item?',
            PatientCreated: 'New patient added succesfully',
            PatientUpdated: 'Patient edited succesfully',
            PatientDeleted: 'Patient deleted succesfully',
            NoteCreated: 'New note added succesfully',
            NoteUpdated: 'Note edited succesfully',
            NoteDeleted: 'Note deleted succesfully',
            PageNotFound: 'Page not found',
        },
        days: [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' ],
        string: 'en-EN',
    }
}

export { LANGUAGES }