export { default as PatientData } from './PatientData'
export { default as PatientFiles } from './PatientFiles'
export { default as PatientNotes } from './PatientNotes'
export { default as PatientPhotos } from './PatientPhotos'
export { default as PatientTreatments } from './PatientTreatments'
export { default as PatientTurns } from './PatientTurns'
